language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
matrix:
  include:
    - python: '3.6'
      env: TOXENV=flake8
sudo: false

before_install:
  - uname -a
  - lsb_release -a
  - python --version
  - virtualenv --version
  - easy_install --version
  - pip --version
install:
  - pip install tox-travis
  - tox --version
  - python setup.py develop
script:
    - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: never
