version: '{branch}-{build}'
build: off
environment:
  matrix:
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
install:
  - pip install tox
test_script:
  - tox
