name: PR validation
on: pull_request

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Test with tox
        run: tox -epy39

      - name: Install pandoc
        run: sudo apt-get install pandoc

      - name: Test python module build
        run: ". .tox/py39/bin/activate; make"

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker images
        run: |
          cd docker; make
